version: '3.9'

services:
  # Quizzify API
  quizzify-api:
    build:
      context: api
      dockerfile: Dockerfile-test
    container_name: quizzify-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - quizzify-api

  ## -----------------------------------------------------------------------------------
  ## ------------------------------------- Database ------------------------------------
  ## -----------------------------------------------------------------------------------

  # PostgreSQL
  db:
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      # Mount the volume to persist the data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Mount the seeds file to populate the database with test data
      - ./db/seeds/seeds-test.sql:/docker-entrypoint-initdb.d/seeds.sql
      # Mount the init script to create the database as an entrypoint to the container
      - postgres_data:/var/lib/postgresql/data
      # Mount .pgpass file to avoid password prompt
      - ./db/.pgpass:/root/.pgpass
    networks:
      - quizzify-api

# Volumes
volumes:
  # PostgreSQL
  postgres_data:

# Networks
networks:
  quizzify-api:
    driver: bridge
